/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.PezDAO;
import modelo.*;
/**
 *
 * @author javie
 */
public class MantenedorListar extends javax.swing.JFrame {

    /**
     * Creates new form CrudPeces
     */
    public MantenedorListar() {
        initComponents();
        PezDAO.llenar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupAtributo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabelVisor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaVisor = new javax.swing.JTextArea();
        jRadioButtonPezDorado = new javax.swing.JRadioButton();
        jRadioButtonPezKoi = new javax.swing.JRadioButton();
        jRadioButtonPezTropical = new javax.swing.JRadioButton();
        jButtonListar = new javax.swing.JButton();
        jRadioButtonTodos = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CRUD DE PECES");

        jLabelVisor.setText("Visor");

        jTextAreaVisor.setColumns(20);
        jTextAreaVisor.setRows(5);
        jScrollPane1.setViewportView(jTextAreaVisor);

        buttonGroupAtributo.add(jRadioButtonPezDorado);
        jRadioButtonPezDorado.setText("Pez Dorado");
        jRadioButtonPezDorado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPezDoradoActionPerformed(evt);
            }
        });

        buttonGroupAtributo.add(jRadioButtonPezKoi);
        jRadioButtonPezKoi.setText("Pez Koi");
        jRadioButtonPezKoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPezKoiActionPerformed(evt);
            }
        });

        buttonGroupAtributo.add(jRadioButtonPezTropical);
        jRadioButtonPezTropical.setText("Pez Tropical");
        jRadioButtonPezTropical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPezTropicalActionPerformed(evt);
            }
        });

        jButtonListar.setText("Listar");
        jButtonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarActionPerformed(evt);
            }
        });

        buttonGroupAtributo.add(jRadioButtonTodos);
        jRadioButtonTodos.setText("Todos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonListar)
                        .addGap(175, 175, 175))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jRadioButtonPezKoi)
                            .addComponent(jLabel1))
                        .addGap(29, 29, 29)
                        .addComponent(jRadioButtonTodos)
                        .addGap(37, 37, 37))))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelVisor)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButtonPezTropical)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonPezDorado))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonPezTropical)
                    .addComponent(jRadioButtonPezDorado)
                    .addComponent(jRadioButtonPezKoi)
                    .addComponent(jRadioButtonTodos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jButtonListar)
                .addGap(17, 17, 17)
                .addComponent(jLabelVisor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonPezDoradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPezDoradoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPezDoradoActionPerformed

    private void jRadioButtonPezKoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPezKoiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPezKoiActionPerformed

    private void jRadioButtonPezTropicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPezTropicalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPezTropicalActionPerformed

    private void jButtonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarActionPerformed
        // TODO add your handling code here:
        
        if(jRadioButtonPezTropical.isSelected()==true){
            jTextAreaVisor.setText("Listado de peces tropicales\n"+
                    "| ID | Especie | Precio | Stock | Color\n\n");
            for(Pez obj: PezDAO.obtenerPezTropical()){
                jTextAreaVisor.append(obj.toString()+"\n");
            }
            
        }
        
        if(jRadioButtonPezDorado.isSelected()==true){
            jTextAreaVisor.setText("Listado de peces dorados\n"+
                    "| ID | Especie | Precio | Stock | Tamaño\n\n");
            for(Pez obj: PezDAO.obtenerPezDorado()){
                jTextAreaVisor.append(obj.toString()+"\n");
            }
        }
        
        if(jRadioButtonPezKoi.isSelected()==true){
            jTextAreaVisor.setText("Listado de peces koi\n"+
                    "| ID | Especie | Precio | Stock | Edad |\n\n");
            for(Pez obj: PezDAO.obtenerPezKoi()){
                jTextAreaVisor.append(obj.toString()+"\n");
            }
        }
        
        if(jRadioButtonTodos.isSelected()==true){
            jTextAreaVisor.setText("");
            for(Pez obj: PezDAO.obtenerDatos()){
                jTextAreaVisor.append(obj.toString()+"\n");
        }
        }
    }//GEN-LAST:event_jButtonListarActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenedorListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenedorListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenedorListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenedorListar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantenedorListar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAtributo;
    private javax.swing.JButton jButtonListar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelVisor;
    private javax.swing.JRadioButton jRadioButtonPezDorado;
    private javax.swing.JRadioButton jRadioButtonPezKoi;
    private javax.swing.JRadioButton jRadioButtonPezTropical;
    private javax.swing.JRadioButton jRadioButtonTodos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaVisor;
    // End of variables declaration//GEN-END:variables
}
