/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlador;
import vista.*;
import controlador.PezDAO;
import modelo.*;
/**
 *
 * @author javie
 */
public class MantenedorPlantilla extends javax.swing.JFrame {

    /**
     * Creates new form CrudPeces
     */
    public MantenedorPlantilla() {
        initComponents();
        PezDAO.llenar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupAtributo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabelVisor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaVisor = new javax.swing.JTextArea();
        jRadioButtonPezDorado = new javax.swing.JRadioButton();
        jRadioButtonPezKoi = new javax.swing.JRadioButton();
        jRadioButtonPezTropical = new javax.swing.JRadioButton();
        jButtonBuscar = new javax.swing.JButton();
        jLabelCategoría = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("MANTENEDOR");

        jLabel2.setText("ID Pez:");

        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });

        jLabelVisor.setText("Visor");

        jTextAreaVisor.setColumns(20);
        jTextAreaVisor.setRows(5);
        jScrollPane1.setViewportView(jTextAreaVisor);

        buttonGroupAtributo.add(jRadioButtonPezDorado);
        jRadioButtonPezDorado.setText("Pez Dorado");
        jRadioButtonPezDorado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPezDoradoActionPerformed(evt);
            }
        });

        buttonGroupAtributo.add(jRadioButtonPezKoi);
        jRadioButtonPezKoi.setText("Pez Koi");
        jRadioButtonPezKoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPezKoiActionPerformed(evt);
            }
        });

        buttonGroupAtributo.add(jRadioButtonPezTropical);
        jRadioButtonPezTropical.setText("Pez Tropical");
        jRadioButtonPezTropical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPezTropicalActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Iniciar busqueda");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabelCategoría.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabelCategoría.setText("Seleccione especie");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelVisor)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jRadioButtonPezTropical)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonPezDorado)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jRadioButtonPezKoi))
                                    .addComponent(jLabelCategoría)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(39, 39, 39)
                                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63)
                                        .addComponent(jButtonBuscar)))))
                        .addGap(33, 33, 33)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(132, 132, 132))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jLabelCategoría)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonPezTropical)
                    .addComponent(jRadioButtonPezDorado)
                    .addComponent(jRadioButtonPezKoi))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBuscar)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(jLabelVisor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jRadioButtonPezDoradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPezDoradoActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jRadioButtonPezDoradoActionPerformed

    private void jRadioButtonPezKoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPezKoiActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jRadioButtonPezKoiActionPerformed

    private void jRadioButtonPezTropicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPezTropicalActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jRadioButtonPezTropicalActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        String IDPez="";
        IDPez = jTextFieldID.getText();
        
        if(jRadioButtonPezDorado.isSelected()==true){
            Pez pez = PezDAO.buscarPezDorado(IDPez);
            if(pez != null){
                jTextAreaVisor.setText("ID: "+pez.getIdPez()+"\n"+
                        "Precio: "+Integer.toString(pez.getPrecio())+"\n"+
                        "Tamaño (cm): "+Integer.toString(((PezDorado) pez).getTamaño())+"\n"+
                        "Stock: "+Integer.toString(pez.getStock()));
                //jTextAreaVisor.setText("Precio: "+Integer.toString(pez.getPrecio()));
                //jTextAreaVisor.setText("Tamaño (cm): "+Integer.toString(((PezDorado) pez).getTamaño()));
                //jTextAreaVisor.setText("Stock: "+Integer.toString(pez.getStock()));
            }else{
                jTextAreaVisor.setText("Error, ID no existe");
            }
        }
        if(jRadioButtonPezKoi.isSelected()==true){
            Pez pez = PezDAO.buscarPezKoi(IDPez);
            if(pez != null){
                jTextAreaVisor.setText("ID: "+pez.getIdPez()+"\n"+
                        "Precio: "+Integer.toString(pez.getPrecio())+"\n"+
                        "Edad: "+Integer.toString(((PezKoi) pez).getEdad())+"\n"+
                        "Stock: "+Integer.toString(pez.getStock()));
            }else{
                jTextAreaVisor.setText("Error, ID no existe");
            }
        }
        if(jRadioButtonPezTropical.isSelected()==true){
            Pez pez = PezDAO.buscar(IDPez);
            if(pez != null){
                jTextAreaVisor.setText("ID: "+pez.getIdPez()+"\n"+
                        "Precio: "+Integer.toString(pez.getPrecio())+"\n"+
                        "Color: "+((PezTropical) pez).getColor()+"\n"+
                        "Stock: "+Integer.toString(pez.getStock()));
            }else{
                jTextAreaVisor.setText("Error, ID no existe");
            }
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    
    public void limpiar(){
        jTextFieldID.setText("");
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MantenedorPlantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MantenedorPlantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MantenedorPlantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MantenedorPlantilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MantenedorPlantilla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAtributo;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelCategoría;
    private javax.swing.JLabel jLabelVisor;
    private javax.swing.JRadioButton jRadioButtonPezDorado;
    private javax.swing.JRadioButton jRadioButtonPezKoi;
    private javax.swing.JRadioButton jRadioButtonPezTropical;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaVisor;
    private javax.swing.JTextField jTextFieldID;
    // End of variables declaration//GEN-END:variables
}
