/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controlador;

import controlador.PezDAO;
import modelo.*;
/**
 *
 * @author javie
 */
public class PlantillaMantenedor extends javax.swing.JFrame {

    /**
     * Creates new form CrudPeces
     */
    public PlantillaMantenedor() {
        initComponents();
        PezDAO.llenar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupAtributo = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabelAtributo = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jTextFieldAtributo = new javax.swing.JTextField();
        jLabelVisor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaVisor = new javax.swing.JTextArea();
        jRadioButtonPezDorado = new javax.swing.JRadioButton();
        jRadioButtonPezKoi = new javax.swing.JRadioButton();
        jRadioButtonPezTropical = new javax.swing.JRadioButton();
        jButtonAgregar = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldPrecio = new javax.swing.JTextField();
        jButtonEliminar = new javax.swing.JButton();
        jButtonModificar = new javax.swing.JButton();
        jButtonListar = new javax.swing.JButton();
        jLabelStock = new javax.swing.JLabel();
        jTextFieldStock = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("CRUD DE PECES");

        jLabel2.setText("ID Pez:");

        jLabelAtributo.setText("Color:");

        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });

        jTextFieldAtributo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAtributoActionPerformed(evt);
            }
        });

        jLabelVisor.setText("Visor");

        jTextAreaVisor.setColumns(20);
        jTextAreaVisor.setRows(5);
        jScrollPane1.setViewportView(jTextAreaVisor);

        buttonGroupAtributo.add(jRadioButtonPezDorado);
        jRadioButtonPezDorado.setText("Pez Dorado");
        jRadioButtonPezDorado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPezDoradoActionPerformed(evt);
            }
        });

        buttonGroupAtributo.add(jRadioButtonPezKoi);
        jRadioButtonPezKoi.setText("Pez Koi");
        jRadioButtonPezKoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPezKoiActionPerformed(evt);
            }
        });

        buttonGroupAtributo.add(jRadioButtonPezTropical);
        jRadioButtonPezTropical.setText("Pez Tropical");
        jRadioButtonPezTropical.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPezTropicalActionPerformed(evt);
            }
        });

        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabel3.setText("Precio:");

        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });

        jButtonListar.setText("Listar");
        jButtonListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarActionPerformed(evt);
            }
        });

        jLabelStock.setText("Stock:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(121, 121, 121))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelVisor)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jRadioButtonPezTropical)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonPezDorado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonPezKoi))
                    .addComponent(jLabelAtributo)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldID, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldStock)
                                            .addComponent(jTextFieldAtributo, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)))))
                            .addComponent(jLabelStock))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonModificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonListar)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonPezTropical, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRadioButtonPezDorado)
                        .addComponent(jRadioButtonPezKoi)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAgregar)
                    .addComponent(jButtonListar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAtributo)
                    .addComponent(jTextFieldAtributo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonModificar)
                    .addComponent(jLabelStock)
                    .addComponent(jTextFieldStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jLabelVisor)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        // TODO add your handling code here:
        String idPez,color="";
        int precio,atributo,stock;
        
        
        idPez = jTextFieldID.getText();
        precio = Integer.parseInt(jTextFieldPrecio.getText());
        atributo = Integer.parseInt(jTextFieldAtributo.getText());
        color = jTextFieldAtributo.getText();
        stock = Integer.parseInt(jTextFieldStock.getText());
        
        Pez pez = null;
        if(jRadioButtonPezDorado.isSelected()==true){
            String especie="Pez Dorado";
            pez = new PezDorado(idPez,especie,precio,atributo,stock);
        }
        
        if(jRadioButtonPezKoi.isSelected()==true){
            String especie="Pez Koi";
            pez = new PezKoi(idPez,atributo,especie,precio,stock);
        }
        
        if(jRadioButtonPezTropical.isSelected()==true){
            String especie="Pez Tropical";
            pez = new PezTropical(idPez,color,especie,precio,stock);
        }
        
        
        if (PezDAO.agregar(pez)== true){
            jTextAreaVisor.setText("Bien, datos agregados");
        }else{
            jTextAreaVisor.setText("Error, datos NO agregados");
        }
        
        limpiar();
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jTextFieldAtributoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAtributoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAtributoActionPerformed

    private void jRadioButtonPezDoradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPezDoradoActionPerformed
        // TODO add your handling code here:
        jLabelAtributo.setText("Tamaño:");
    }//GEN-LAST:event_jRadioButtonPezDoradoActionPerformed

    private void jRadioButtonPezKoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPezKoiActionPerformed
        // TODO add your handling code here:
        jLabelAtributo.setText("Edad:");
    }//GEN-LAST:event_jRadioButtonPezKoiActionPerformed

    private void jRadioButtonPezTropicalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPezTropicalActionPerformed
        // TODO add your handling code here:
        jLabelAtributo.setText("Color:");
    }//GEN-LAST:event_jRadioButtonPezTropicalActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        String IDPez="";
        IDPez = jTextFieldID.getText();
        
        if(jRadioButtonPezDorado.isSelected()==true){
            Pez pez = PezDAO.buscar(IDPez);
            if(pez != null){
                jTextFieldPrecio.setText(Integer.toString(pez.getPrecio()));
                jTextFieldAtributo.setText(Integer.toString(((PezDorado) pez).getTamaño()));
            }else{
                jTextAreaVisor.setText("Error, ID no existe");
            }
        }
        if(jRadioButtonPezKoi.isSelected()==true){
            Pez pez = PezDAO.buscar(IDPez);
            if(pez != null){
                jTextFieldPrecio.setText(Integer.toString(pez.getPrecio()));
                jTextFieldAtributo.setText(Integer.toString(((PezKoi) pez).getEdad()));
            }else{
                jTextAreaVisor.setText("Error, ID no existe");
            }
        }
        if(jRadioButtonPezTropical.isSelected()==true){
            Pez pez = PezDAO.buscar(IDPez);
            if(pez != null){
                jTextFieldPrecio.setText(Integer.toString(pez.getPrecio()));
                jTextFieldAtributo.setText(((PezTropical) pez).getColor());
            }else{
                jTextAreaVisor.setText("Error, ID no existe");
            }
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarActionPerformed
        // TODO add your handling code here:
        jTextAreaVisor.setText("");
        for(Pez obj: PezDAO.obtenerDatos()){
            jTextAreaVisor.append(obj.toString()+"\n");
        }
    }//GEN-LAST:event_jButtonListarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        // TODO add your handling code here:
        String IDPez="";
        
        IDPez = jTextFieldID.getText();
        
        if(PezDAO.eliminar(IDPez)==true){
            limpiar();
            jTextAreaVisor.setText("Bien, datos eliminados");
        }else{
            jTextAreaVisor.setText("Error, ID no existe");
        }
    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
        
        String idPez,color="";
        int precio, atributo;
        
        idPez = jTextFieldID.getText();
        precio = Integer.parseInt(jTextFieldPrecio.getText());
        atributo = Integer.parseInt(jTextFieldAtributo.getText());
        color = jTextFieldAtributo.getText();
        
        if(jRadioButtonPezDorado.isSelected()==true){
            String especie="Pez Dorado";
            Pez pez = new PezDorado(idPez,especie,precio,atributo);
            
            if (PezDAO.modificar(pez)== true){
            jTextAreaVisor.setText("Bien, datos modificados");
            }else{
            jTextAreaVisor.setText("Error, datos NO modificados");
            }
        }
        
        if(jRadioButtonPezKoi.isSelected()==true){
            String especie="Pez Koi";
            Pez pez = new PezKoi(idPez,atributo,especie,precio);
            
            if (PezDAO.modificar(pez)== true){
            jTextAreaVisor.setText("Bien, datos modificados");
            }else{
            jTextAreaVisor.setText("Error, datos NO modificados");
            }
        }
        
        if(jRadioButtonPezTropical.isSelected()==true){
            String especie="Pez Tropical";
            Pez pez = new PezTropical(idPez,color,especie,precio);
            
            if (PezDAO.modificar(pez)== true){
            jTextAreaVisor.setText("Bien, datos modificados");
            }else{
            jTextAreaVisor.setText("Error, datos NO modificados");
            }
        }
        
        limpiar();
    }//GEN-LAST:event_jButtonModificarActionPerformed

    
    public void limpiar(){
        jTextFieldID.setText("");
        jTextFieldPrecio.setText("");
        jTextFieldAtributo.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlantillaMantenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlantillaMantenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlantillaMantenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlantillaMantenedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlantillaMantenedor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupAtributo;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonListar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAtributo;
    private javax.swing.JLabel jLabelStock;
    private javax.swing.JLabel jLabelVisor;
    private javax.swing.JRadioButton jRadioButtonPezDorado;
    private javax.swing.JRadioButton jRadioButtonPezKoi;
    private javax.swing.JRadioButton jRadioButtonPezTropical;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaVisor;
    private javax.swing.JTextField jTextFieldAtributo;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldPrecio;
    private javax.swing.JTextField jTextFieldStock;
    // End of variables declaration//GEN-END:variables
}
